# Uncomment the next line to define a global platform for your project
 platform :ios, '8.0'

target 'GOpenSource_AppKit' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
  #source 'https://github.com/gizwits/PodSpecs.git'

#pod 'GizWifiSDK','2.04.04'

  # Pods for GOpenSource_AppKit

end
